# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'urban-waddle' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for urban-waddle
  pod 'Masonry'
  pod 'AFNetworking', '~> 3.0'

  target 'urban-waddleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'urban-waddleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
